### ISSUE TITLE
I can not enter the URL

### ISSUE THREAD

**Issue by iwansetwan** [fastscape-lem/s2s-future-dragonstone#8]
Hi Benoit,

I try to use docker but I have trouble with the URL it doesn't work for me even though I did not use proxy.
Could you help me?
Thank you very much.

Regards,
Iwan Setiawan
University of Rennes 1

**Comment by benbovy** [comment]
Hi Iwan,

Could you tell me which platform do you use? Could you also show here the output of the command(s) that you have run in the terminal?

**Comment by iwansetwan** [comment]
I use windows 10. 
![image](https://user-images.githubusercontent.com/77268361/104198439-857d3d80-5426-11eb-9406-a9bb1c2eec50.png)
![image](https://user-images.githubusercontent.com/77268361/104198548-a34aa280-5426-11eb-9925-ec9ab418c22a.png)
![image](https://user-images.githubusercontent.com/77268361/104198592-b52c4580-5426-11eb-9511-2a2c898ac77f.png)

**Comment by benbovy** [comment]
Could you try what I have suggested in #7 ?

**Comment by benbovy** [comment]
I see from the screenshots that you seem to be running the `docker run` command from the container itself. Did you use the Docker dashboard to run the docker image? The `docker run` command line in the README file is for running the container with specific option, so you should run it from outside the docker dashboard, like the `docker pull` command.

**Comment by iwansetwan** [comment]
That works! Thanks

**Comment by benbovy** [comment]
Ok great!

**Comment by iwansetwan** [comment]
So, everytime I would like to open the Jupyter notebook, I have to run the command "docker run........." ?

**Comment by benbovy** [comment]
> everytime I would like to open the Jupyter notebook, I have to run the command "docker run........." ?

Not if the container is still running, i.e., if you haven't stopped it using

```
docker stop dragonstone
docker rm dragonstone
```

Jupyter is a server running in the background (inside the docker container), so if you close the tab in your browser but you haven't stopped the container, the application is still running and you can just open a tab in your browser and enter the url/token again to re-open Jupyterlab.
